# Example Requirements.yml
# =======================
#
- src: https://mygitsite/dept/app1
  version: 0.1
  name: app1
  scm: git

- src: https://mygitsite/dept/app2
  version: 0.1
  name: app2
  scm: git
